# -*- coding: utf-8 -*-
"""image to Pencil Sketch with Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j5Z8iyxz8sqeVF4VZ75Ta_KNA9EzrzWD
"""

import cv2
import numpy as np
from matplotlib import pyplot as plt
img = cv2.imread('/content/dog.jpg')

gray_image = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

inverted_gray_image = 255 - gray_image

blurred_image = cv2.GaussianBlur(inverted_gray_image, (21, 21), 0)

sketch_image = cv2.divide(gray_image, 255 - blurred_image, scale=256)

plt.imshow(sketch_image, cmap='gray')
plt.show()

cv2.imwrite('output_s=  ` `44ketch.jpg', sketch_image)